### ISSUE TITLE
Kubeflow demo error

### ISSUE THREAD

**Issue by dkurt** [IntelAI/OpenVINO-model-server#132]
Hi!

Just tried to run Kubeflow pipelines demo and caught this error: `Internal compiler error: Found unresolved PipelineParam.`

Ubuntu 18.04, kubeflow pipelines v0.1.40

```
OpenVINO-model-server/example_kubeflow_pipelines/ovms_deployer$ /usr/local/bin/dsl-compile --py deployer.py --output deployer.tar.gz

/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.6/dist-packages/kfp/dsl/_metadata.py:67: UserWarning: Explicit creation of `kfp.dsl.PipelineParam`s by the users is deprecated. The users should define the parameter type and default values using standard pythonic constructs: def my_func(a: int = 1, b: str = "default"):
  warnings.warn('Explicit creation of `kfp.dsl.PipelineParam`s by the users is deprecated. The users should define the parameter type and default values using standard pythonic constructs: def my_func(a: int = 1, b: str = "default"):')
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=model-export-path}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=model-export-path}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=server-name}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=server-name}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=log-level}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=log-level}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=batch-size}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=batch-size}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=model-version-policy}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=model-version-policy}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=replicas}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=replicas}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=evaluation-images-list}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=evaluation-images-list}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=image-path-prefix}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=image-path-prefix}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=model-input-name}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=model-input-name}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=model-output-name}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=model-output-name}}".
  serialized_value),
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:133: UserWarning: Missing type name was inferred as "PipelineParam" based on the value "{{pipelineparam:op=;name=model-input-size}}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/usr/local/lib/python3.6/dist-packages/kfp/components/_data_passing.py:154: UserWarning: There are no registered serializers from type "PipelineParam" to type "PipelineParam", so the value will be serializers as string "{{pipelineparam:op=;name=model-input-size}}".
  serialized_value),
Traceback (most recent call last):
  File "/usr/local/bin/dsl-compile", line 11, in <module>
    load_entry_point('kfp==0.1.40', 'console_scripts', 'dsl-compile')()
  File "/usr/local/lib/python3.6/dist-packages/kfp/compiler/main.py", line 123, in main
    compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
  File "/usr/local/lib/python3.6/dist-packages/kfp/compiler/main.py", line 112, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/usr/local/lib/python3.6/dist-packages/kfp/compiler/main.py", line 71, in _compile_pipeline_function
    kfp.compiler.Compiler().compile(pipeline_func, output_path, type_check)
  File "/usr/local/lib/python3.6/dist-packages/kfp/compiler/compiler.py", line 879, in compile
    package_path=package_path)
  File "/usr/local/lib/python3.6/dist-packages/kfp/compiler/compiler.py", line 942, in _create_and_write_workflow
    self._write_workflow(workflow, package_path)
  File "/usr/local/lib/python3.6/dist-packages/kfp/compiler/compiler.py", line 897, in _write_workflow
    'Internal compiler error: Found unresolved PipelineParam. '
```

**Comment by dkurt** [comment]
Looks like with 0.1.20 it works fine
```sh
python3 -m pip install https://storage.googleapis.com/ml-pipeline/release/0.1.20/kfp.tar.gz --upgrade
```

**Comment by dkurt** [comment]
Next question is that
```
/usr/local/bin/dsl-compile --py deployer.py --output deployer.tar.gz
```
doe not produce any useful logs but documentation has no further steps

**Comment by dkurt** [comment]
@dtrawins, @mzegla, Hi! May I ask you to point which steps should go after `dsl-compile` at https://github.com/IntelAI/OpenVINO-model-server/tree/master/example_kubeflow_pipelines/ovms_deployer and https://github.com/IntelAI/OpenVINO-model-server/tree/master/example_kubeflow_pipelines/openvino guides? And what's the difference between them?

**Comment by dtrawins** [comment]
@dkurt  Once you genereate deployer.tar.gz file, you can import it in KubeFlow Pipeline GUI interface. When the pipeline is imported you are create an experiment, which should work with the default parameters.

**Comment by dkurt** [comment]
Do you know the best way to deploy Kubeflow pipelines locally? Based on my experience, it's now straightforward: https://github.com/kubeflow/website/pull/1609, https://github.com/canonical-labs/kubeflow-tools/issues/15

There are three ways to Getting Started with KF: https://www.kubeflow.org/docs/started/workstation/getting-started-linux/ but neither of them works for me.

**Comment by dtrawins** [comment]
So far I was testing kubeflow pipelines in GCP. I can ask my colleagues, tough. If they can share some tips, I'll send it via email.

**Comment by dkurt** [comment]
@dtrawins, Thanks!

I could run Kubeflow locally with https://github.com/kubeflow/website/blob/master/content/docs/other-guides/virtual-dev/getting-started-multipass.md#install-kubeflow-using-microk8s. Have not tried OVMS with it yet.

**Comment by dkurt** [comment]
@dtrawins, Can you please guide me in which order should I import [deployer.tar.gz](https://github.com/IntelAI/OpenVINO-model-server/tree/master/example_kubeflow_pipelines/ovms_deployer) and [openvino-pipeline.tar.gz](https://github.com/IntelAI/OpenVINO-model-server/tree/master/example_kubeflow_pipelines/openvino)? Just tried to import ovms-deployer first then `Create experiment` but got `This step is in Failed state with this message: failed with exit code 4`. No logs, no output error:
![image](https://user-images.githubusercontent.com/25801568/74090727-cefb3500-4abf-11ea-8efb-87dc690bbad3.png)

**Comment by dkurt** [comment]
Ok, could find it by Run id:

erorr: `executor error: open /tmp/server_endpoint: no such file or directory`

```
sudo cat /var/log/pods/kubeflow_ovms-deployment-pipeline-2dqss-997491131_d40365a6-1aaf-46b6-ae61-c4f6271f54c1/wait/0.log 
2020-02-09T12:18:31.509880916+03:00 stderr F time="2020-02-09T09:18:31Z" level=info msg="Creating PNS executor (namespace: kubeflow, pod: ovms-deployment-pipeline-2dqss-997491131, pid: 6, hasOutputs: true)"
2020-02-09T12:18:31.510967702+03:00 stderr F time="2020-02-09T09:18:31Z" level=info msg="Executor (version: v2.3.0, build_date: 2019-05-20T22:10:54Z) initialized (pod: kubeflow/ovms-deployment-pipeline-2dqss-997491131) with template:\n{\"name\":\"deploy-openvino-model-server\",\"inputs\":{\"parameters\":[{\"name\":\"batch-size\",\"value\":\"auto\"},{\"name\":\"log-level\",\"value\":\"DEBUG\"},{\"name\":\"model-export-path\",\"value\":\"gs://intelai_public_models/resnet_50_i8\"},{\"name\":\"model-version-policy\",\"value\":\"{\\\"latest\\\": { \\\"num_versions\\\":2 }}\"},{\"name\":\"replicas\",\"value\":\"1\"},{\"name\":\"server-name\",\"value\":\"resnet\"}]},\"outputs\":{\"parameters\":[{\"name\":\"deploy-openvino-model-server-output\",\"valueFrom\":{\"path\":\"/tmp/server_endpoint\"}}],\"artifacts\":[{\"name\":\"mlpipeline-ui-metadata\",\"path\":\"/mlpipeline-ui-metadata.json\",\"optional\":true},{\"name\":\"mlpipeline-metrics\",\"path\":\"/mlpipeline-metrics.json\",\"optional\":true}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"intelaipg/kubeflow-pipeline-ovms-deployer:0.1\",\"command\":[\"./deploy.sh\"],\"args\":[\"--model-export-path\",\"gs://intelai_public_models/resnet_50_i8\",\"--server-name\",\"resnet\",\"--log-level\",\"DEBUG\",\"--batch-size\",\"auto\",\"--model-version-policy\",\"{\\\"latest\\\": { \\\"num_versions\\\":2 }}\",\"--replicas\",\"1\"],\"resources\":{}},\"archiveLocation\":{\"s3\":{\"endpoint\":\"minio:9000\",\"bucket\":\"mlpipeline\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"secretkey\"},\"key\":\"artifacts/ovms-deployment-pipeline-2dqss/ovms-deployment-pipeline-2dqss-997491131\"}}}"
2020-02-09T12:18:31.511005949+03:00 stderr F time="2020-02-09T09:18:31Z" level=info msg="Waiting on main container"
2020-02-09T12:18:31.511273799+03:00 stderr F time="2020-02-09T09:18:31Z" level=warning msg="Polling root processes (1m0s)"
2020-02-09T12:18:46.925400689+03:00 stderr F time="2020-02-09T09:18:46Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:46.983136519+03:00 stderr F time="2020-02-09T09:18:46Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.03427189+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.08385669+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.134292913+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.184742299+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.235223813+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.339537547+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.339604412+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.387329963+03:00 stderr F time="2020-02-09T09:18:47Z" level=warning msg="Failed to stat /proc/20/root: stat /proc/20/root: permission denied"
2020-02-09T12:18:47.437758799+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239917 676916867} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.437791273+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="Secured filehandle on /proc/20/root"
2020-02-09T12:18:47.437881932+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="containerID 9393a8bbb7f6da22a9442b115d68f664bc186ce529aa08cb14fa622644c57e29 mapped to pid 20"
2020-02-09T12:18:47.488454419+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239917 676916867} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.538809449+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239917 676916867} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.589327157+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239917 676916867} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.63971113+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239917 676916867} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.690181697+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.740690223+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.791014549+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.834125698+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="main container started with container ID: 9393a8bbb7f6da22a9442b115d68f664bc186ce529aa08cb14fa622644c57e29"
2020-02-09T12:18:47.834141984+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="Starting annotations monitor"
2020-02-09T12:18:47.841404049+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.891848946+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.942296006+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:47.992715249+03:00 stderr F time="2020-02-09T09:18:47Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:48.043200156+03:00 stderr F time="2020-02-09T09:18:48Z" level=info msg="pid 20: &{root 4096 2147484141 {360554658 63716836711 0x22af420} {6291535 12720466 1 16877 0 0 0 0 4096 4096 8 {1581239927 665477419} {1581239911 360554658} {1581239927 25441947} [0 0 0]}}"
2020-02-09T12:18:48.076417088+03:00 stderr F time="2020-02-09T09:18:48Z" level=info msg="Main pid identified as 20"
2020-02-09T12:18:48.07644112+03:00 stderr F time="2020-02-09T09:18:48Z" level=info msg="Successfully secured file handle on main container root filesystem"
2020-02-09T12:18:48.076450124+03:00 stderr F time="2020-02-09T09:18:48Z" level=info msg="Waiting for main pid 20 to complete"
2020-02-09T12:18:48.076453999+03:00 stderr F time="2020-02-09T09:18:48Z" level=info msg="Starting deadline monitor"
2020-02-09T12:18:48.093604522+03:00 stderr F time="2020-02-09T09:18:48Z" level=info msg="Stopped root processes polling due to successful securing of main root fs"
2020-02-09T12:18:49.074121001+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="Main pid 20 completed"
2020-02-09T12:18:49.074137486+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="Main container completed"
2020-02-09T12:18:49.074141782+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="No sidecars"
2020-02-09T12:18:49.07414514+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="Saving output parameters"
2020-02-09T12:18:49.074148456+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="Saving path output parameter: deploy-openvino-model-server-output"
2020-02-09T12:18:49.074152758+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="Copying /tmp/server_endpoint from base image layer"
2020-02-09T12:18:49.074262079+03:00 stderr F time="2020-02-09T09:18:49Z" level=error msg="executor error: open /tmp/server_endpoint: no such file or directory"
2020-02-09T12:18:49.074331678+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="Alloc=3804 TotalAlloc=21728 Sys=70334 NumGC=8 Goroutines=9"
2020-02-09T12:18:49.074629043+03:00 stderr F time="2020-02-09T09:18:49Z" level=info msg="Annotations monitor stopped"
2020-02-09T12:18:49.08018992+03:00 stderr F time="2020-02-09T09:18:49Z" level=fatal msg="open /tmp/server_endpoint: no such file or directory"
```

**Comment by dkurt** [comment]
Tried to deploy ovms_deployer on Azure. Same thing:

```
+ shift
+ export MODEL_EXPORT_PATH=gs://intelai_public_models/resnet_50_i8
+ MODEL_EXPORT_PATH=gs://intelai_public_models/resnet_50_i8
+ shift
+ (( 10 ))
+ case $1 in
+ shift
+ SERVER_NAME=resnet
+ shift
+ (( 8 ))
+ case $1 in
+ shift
+ export LOG_LEVEL=DEBUG
+ LOG_LEVEL=DEBUG
+ shift
+ (( 6 ))
+ case $1 in
+ shift
+ export BATCH_SIZE=auto
+ BATCH_SIZE=auto
+ shift
+ (( 4 ))
+ case $1 in
+ shift
+ export 'MODEL_VERSION_POLICY={"latest": { "num_versions":2 }}'
+ MODEL_VERSION_POLICY='{"latest": { "num_versions":2 }}'
+ shift
+ (( 2 ))
+ case $1 in
+ shift
+ export REPLICAS=1
+ REPLICAS=1
+ shift
+ (( 0 ))
+ '[' -z gs://intelai_public_models/resnet_50_i8 ']'
+ echo 'Deploying the model '\''gs://intelai_public_models/resnet_50_i8'\'''
+ '[' -z '' ']'
Deploying the model 'gs://intelai_public_models/resnet_50_i8'
++ wget -q -O- '--header=Metadata-Flavor: Google' 
http://metadata.google.internal/computeMetadata/v1/instance/attributes/cluster-name
+ CLUSTER_NAME=
```
![image](https://user-images.githubusercontent.com/25801568/74104702-5b613280-4b68-11ea-8bf5-8084a057c86d.png)

**Comment by dkurt** [comment]
Succeed to run a demo on Azure. Looks like Kubeflow for now at the state of active development and there are a lot of docs and deployment guides which just do not work. Thanks!
